; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32
extra_configs = 
	app_secrets_empty.ini
	app_secrets.ini

[app_default_settings]
build_flags = 
	-D ACCESS_POINT_ESSID='"RopeSnap"'
	-D ACCESS_POINT_IP="IPAddress(192, 168, 4, 1)"
	-D ACCESS_POINT_GATEWAY="IPAddress(192, 168, 4, 1)"
	-D ACCESS_POINT_SUBNET="IPAddress(255, 255, 255, 0)"

[env]
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
build_flags = 
	${app_default_settings.build_flags}
	${app_secrets.build_flags}
custom_ap_pwd_length = 20
extra_scripts = 
	pre:scripts/install_python_dependencies.py
	pre:scripts/generate_app_secrets.py
	pre:scripts/build_web_interface.py
lib_compat_mode = strict

[env:esp12e]
platform = espressif8266
board = esp12e
build_flags = 
	${env.build_flags}
	-D HX711_DOUT_PIN=12
	-D HX711_SCK_PIN=13
	-D DS18B20_PIN=14
lib_deps = 
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
	esp32async/ESPAsyncWebServer@^3.10.3
	esp32async/ESPAsyncTCP@^2.0.0
	bogde/HX711@^0.7.5
	bblanchon/ArduinoJson @ ^7.4.3
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit SH110X@^2.1.14

[env:esp32]
platform = espressif32
board = az-delivery-devkit-v4
board_build.mcu = esp32
build_flags = 
	${env.build_flags}
	-D HX711_DOUT_PIN=19
	-D HX711_SCK_PIN=23
	-D DS18B20_PIN=18
lib_deps = 
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
	esp32async/ESPAsyncWebServer@^3.10.3
	esp32async/AsyncTCP@^3.4.10
	bogde/HX711@^0.7.5
	bblanchon/ArduinoJson @ ^7.4.3
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit SH110X@^2.1.14
